const urls = [
  "https://citaty.info/rating/best?page=0",
  "https://citaty.info/rating/best?page=1",
  "https://citaty.info/rating/best?page=2",
  "https://citaty.info/rating/best?page=3",
  "https://citaty.info/rating/best?page=4",
  "https://citaty.info/rating/best?page=5",
  "https://citaty.info/rating/best?page=6",

  "https://citaty.info/category/citaty-so-smyslom?page=0",
  "https://citaty.info/category/citaty-so-smyslom?page=1",
  "https://citaty.info/category/citaty-so-smyslom?page=2",
  "https://citaty.info/category/citaty-so-smyslom?page=3",
  "https://citaty.info/category/citaty-so-smyslom?page=4",
  "https://citaty.info/category/citaty-so-smyslom?page=5",
  "https://citaty.info/category/citaty-so-smyslom?page=6",
  "https://citaty.info/category/citaty-so-smyslom?page=7",
  "https://citaty.info/category/citaty-so-smyslom?page=8",
  "https://citaty.info/category/citaty-so-smyslom?page=9",
  "https://citaty.info/category/citaty-so-smyslom?page=11",
  "https://citaty.info/category/citaty-so-smyslom?page=12",
  "https://citaty.info/category/citaty-so-smyslom?page=13",
  "https://citaty.info/category/citaty-so-smyslom?page=14",
  "https://citaty.info/category/citaty-so-smyslom?page=15",
  "https://citaty.info/category/citaty-so-smyslom?page=16",
  "https://citaty.info/category/citaty-so-smyslom?page=17",
  "https://citaty.info/category/citaty-so-smyslom?page=18",
  "https://citaty.info/category/citaty-so-smyslom?page=19",
  "https://citaty.info/category/citaty-so-smyslom?page=20",
  "https://citaty.info/category/citaty-so-smyslom?page=21",
  "https://citaty.info/category/citaty-so-smyslom?page=22",
  "https://citaty.info/category/citaty-so-smyslom?page=23",
  "https://citaty.info/category/citaty-so-smyslom?page=24",
  "https://citaty.info/category/citaty-so-smyslom?page=25",
  "https://citaty.info/category/citaty-so-smyslom?page=26",
  "https://citaty.info/category/citaty-so-smyslom?page=27",
  "https://citaty.info/category/citaty-so-smyslom?page=28",
  "https://citaty.info/category/citaty-so-smyslom?page=29",
  "https://citaty.info/category/citaty-so-smyslom?page=30",


];

export default urls;
